USAGE_LOG_FILE = "whatsapp_usage_log.json"
AUDIT_LOG_FILE = "whatsapp_audit_log.jsonl"
CHROME_PROFILE_DIR = "chrome-profile"

MAX_GROUPS_PER_SESSION = 30
MAX_GROUPS_PER_DAY = 60
MAX_GROUPS_PER_TURN = 30
MAX_CONSECUTIVE_ERRORS = 3

WINDOW_WIDTH = 600
WINDOW_HEIGHT = 720
